env:
    browser: true

settings:
    react:
        version: 'detect'

parserOptions:
    project:
        - ./tsconfig.json

extends:
    - ../.eslintrc.yml
    - plugin:react/recommended
    - plugin:react/jsx-runtime
    - plugin:react-hooks/recommended
    - plugin:jsx-a11y/recommended

rules:
    react/prop-types:
        - off
    react/jsx-no-bind:
        - error
        - ignoreRefs: true

overrides:
    - files:
          - vite.config.ts
      rules:
          import/no-default-export:
              - off
          react/jsx-no-bind:
              - off
    - files:
          - vite-env.d.ts
      rules:
          unicorn/prevent-abbreviations:
              - off
    - files:
          - src/bundles/common/components/ui/*.tsx
      rules:
          unicorn/prevent-abbreviations:
              - off
          '@typescript-eslint/consistent-type-definitions':
              - off
          no-restricted-syntax:
              - off
