const AppRoute = {
    ROOT: '/',
    SIGN_IN: '/sign-in',
    SIGN_UP: '/sign-up',
    ADMIN_ROOT: '/admin',
    ADMIN_DASHBOARD: '/admin/dashboard',
    ADMIN_ORDERS: '/admin/orders',
    ADMIN_ORDER_$ID: '/admin/orders/:id',
    ADMIN_ORDER_CREATE: '/admin/orders/create',
    ADMIN_PRODUCTS: '/admin/products',
    ADMIN_PRODUCT_$ID: '/admin/products/:id',
    ADMIN_PRODUCT_CREATE: '/admin/products/create',
    ADMIN_ANALYTICS: '/admin/analytics',
    ADMIN_MANAGERS: '/admin/managers',
    ADMIN_PROFILE: '/admin/profile',
    SIGN_UP_MANAGER: '/sign-up-manager',
    CONFIRM_EMAIL: '/confirm-email',
    PROFILE: '/profile',
    MY_ORDERS: '/my-orders',
    MY_ORDER_$ID: '/my-orders/:id',
    MY_ORDER_CREATE: '/my-orders/create',
    NOT_FOUND: '*',
} as const;

export { AppRoute };
